### ISSUE TITLE
Group by region

### ISSUE THREAD

**Issue by rgaudin** [kiwix/mirrors-qa#41]
Following #38, #39 and #40, we'll want the dashboard to be able to output some data by region. It might be copy of Country-version that uses a group-by-region. We obviously want to keep the country versions as well.

Exact list to be determined but at least:

- Region profile
- Mirror profile that shows data per region
- Mirror/Region matcher

**Comment by elfkuzco** [comment]
I have updated the dashboard with region data. Given there's a long list of countries and the information in it would contain too many rows once we switch to a provider that supports more countries, I have removed some of the country questions from the dashboard and saved them as regular questions with `-Country Version` suffix.

I left ones like the country detail which is more narrow and more helpful for one to drill through. What do you think?

**Comment by elfkuzco** [comment]
Um, I left out the Mirror/Region matcher since the _Region profile_ shows the top mirrors for the region and the _Mirror profile_ shows the top regions for the mirror. Given the data points are few (7 regions by 13 mirrors), I think these two serve as some sort of recommendation or _matching_.

As such, I left the _Top Countries_ and _Top Mirrors_ to work at country level to allow for drilling down to the base level. What do you think?

**Comment by rgaudin** [comment]
Thank you ; I believe that's fine as well.
